import type { Ticket } from "./types"

export const mockTickets: Ticket[] = [
  {
    id: "ticket-1",
    title: "Trackpad not clicking",
    summary: "The trackpad's left click has stopped registering intermittently since this morning.",
    status: "open",
    laptopId: "laptop-1",
    raisedByEmail: "jane.doe@laptrac.dev",
    raisedByName: "Jane Doe",
    assignedToEmail: null,
    assignedToName: null,
    createdAt: "2026-08-26T08:12:00.000Z",
    comments: [],
  },
  {
    id: "ticket-2",
    title: "Battery draining fast",
    summary: "Battery goes from 100% to 20% in under two hours even with light use.",
    status: "claimed",
    laptopId: "laptop-3",
    raisedByEmail: "amara.okafor@laptrac.dev",
    raisedByName: "Amara Okafor",
    assignedToEmail: "bob.smith@laptrac.dev",
    assignedToName: "Bob Smith",
    createdAt: "2026-08-22T14:40:00.000Z",
    comments: [
      {
        id: "comment-1",
        authorEmail: "bob.smith@laptrac.dev",
        authorName: "Bob Smith",
        message: "Picked this up, running a battery health diagnostic now.",
        createdAt: "2026-08-23T09:05:00.000Z",
      },
    ],
  },
  {
    id: "ticket-3",
    title: "Keyboard keys sticking",
    summary: "The 'E' and 'R' keys stick occasionally, needs a hardware repair.",
    status: "resolved",
    laptopId: "laptop-5",
    raisedByEmail: "amara.okafor@laptrac.dev",
    raisedByName: "Amara Okafor",
    assignedToEmail: "bob.smith@laptrac.dev",
    assignedToName: "Bob Smith",
    createdAt: "2026-08-18T10:00:00.000Z",
    comments: [
      {
        id: "comment-2",
        authorEmail: "bob.smith@laptrac.dev",
        authorName: "Bob Smith",
        message: "Swapped the keyboard assembly, all keys tested fine now.",
        createdAt: "2026-08-19T15:30:00.000Z",
      },
    ],
  },
  {
    id: "ticket-4",
    title: "Need a second monitor adapter",
    summary: "Requesting a USB-C to HDMI adapter for my home office setup.",
    status: "open",
    laptopId: "laptop-1",
    raisedByEmail: "jane.doe@laptrac.dev",
    raisedByName: "Jane Doe",
    assignedToEmail: null,
    assignedToName: null,
    createdAt: "2026-08-27T11:20:00.000Z",
    comments: [],
  },
  {
    id: "ticket-5",
    title: "Wi-Fi drops randomly",
    summary: "Wi-Fi disconnects a few times a day and needs a manual reconnect.",
    status: "claimed",
    laptopId: "laptop-2",
    raisedByEmail: "bob.smith@laptrac.dev",
    raisedByName: "Bob Smith",
    assignedToEmail: "bob.smith@laptrac.dev",
    assignedToName: "Bob Smith",
    createdAt: "2026-08-24T09:00:00.000Z",
    comments: [],
  },
  {
    id: "ticket-6",
    title: "Screen flickers on startup",
    summary: "Display flickers for about 10 seconds after waking from sleep.",
    status: "resolved",
    laptopId: "laptop-3",
    raisedByEmail: "amara.okafor@laptrac.dev",
    raisedByName: "Amara Okafor",
    assignedToEmail: "bob.smith@laptrac.dev",
    assignedToName: "Bob Smith",
    createdAt: "2026-08-10T13:00:00.000Z",
    comments: [],
  },
]
