import type { Laptop } from "./types"

export const mockLaptops: Laptop[] = [
  {
    id: "laptop-1",
    brand: "Apple",
    model: "MacBook Pro 14",
    os: "macOS Sonoma",
    serialNumber: "LT-2024-0001",
    status: "assigned",
    assignedToEmail: "jane.doe@laptrac.dev",
    assignedToName: "Jane Doe",
    history: [
      {
        id: "history-1",
        type: "assigned",
        note: "Assigned to Jane Doe",
        actorName: "Bob Smith",
        createdAt: "2026-07-02T09:15:00.000Z",
      },
    ],
  },
  {
    id: "laptop-2",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon",
    os: "Windows 11",
    serialNumber: "LT-2023-0142",
    status: "assigned",
    assignedToEmail: "bob.smith@laptrac.dev",
    assignedToName: "Bob Smith",
    history: [
      {
        id: "history-2",
        type: "assigned",
        note: "Assigned to Bob Smith",
        actorName: "Bob Smith",
        createdAt: "2025-11-14T10:00:00.000Z",
      },
    ],
  },
  {
    id: "laptop-3",
    brand: "Dell",
    model: "XPS 13",
    os: "Windows 11",
    serialNumber: "LT-2023-0098",
    status: "assigned",
    assignedToEmail: "amara.okafor@laptrac.dev",
    assignedToName: "Amara Okafor",
    history: [
      {
        id: "history-3",
        type: "assigned",
        note: "Assigned to Amara Okafor",
        actorName: "Bob Smith",
        createdAt: "2025-09-01T13:30:00.000Z",
      },
    ],
  },
  {
    id: "laptop-4",
    brand: "Apple",
    model: "MacBook Air M2",
    os: "macOS Sonoma",
    serialNumber: "LT-2024-0033",
    status: "available",
    assignedToEmail: null,
    assignedToName: null,
    history: [],
  },
  {
    id: "laptop-5",
    brand: "Lenovo",
    model: "ThinkPad T14",
    os: "Windows 11",
    serialNumber: "LT-2022-0067",
    status: "in-repair",
    assignedToEmail: null,
    assignedToName: null,
    history: [
      {
        id: "history-4",
        type: "repair",
        note: "Keyboard replacement in progress",
        actorName: "Bob Smith",
        createdAt: "2026-08-20T08:45:00.000Z",
      },
      {
        id: "history-5",
        type: "unassigned",
        note: "Unassigned for repair",
        actorName: "Bob Smith",
        createdAt: "2026-08-19T16:20:00.000Z",
      },
    ],
  },
  {
    id: "laptop-6",
    brand: "Microsoft",
    model: "Surface Laptop 5",
    os: "Windows 11",
    serialNumber: "LT-2023-0210",
    status: "available",
    assignedToEmail: null,
    assignedToName: null,
    history: [],
  },
  {
    id: "laptop-7",
    brand: "Apple",
    model: "MacBook Pro 13",
    os: "macOS Ventura",
    serialNumber: "LT-2021-0019",
    status: "retired",
    assignedToEmail: null,
    assignedToName: null,
    history: [
      {
        id: "history-6",
        type: "note",
        note: "Retired - end of life",
        actorName: "Bob Smith",
        createdAt: "2026-06-10T11:00:00.000Z",
      },
    ],
  },
  {
    id: "laptop-8",
    brand: "Dell",
    model: "Latitude 7420",
    os: "Windows 10",
    serialNumber: "LT-2022-0150",
    status: "available",
    assignedToEmail: null,
    assignedToName: null,
    history: [],
  },
]
